version: "3.8"
services:
  bookstore-users-db:
    container_name: bookstore-users-db
    image: mcr.microsoft.com/mssql/server:2022-CU10-ubuntu-22.04
    environment:
      - MSSQL_SA_PASSWORD=rbook#Pass3210
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - ./data/mssql/data:/var/opt/mssql/data
      - ./data/mssql/log:/var/opt/mssql/log
      - ./data/mssql/secrets:/var/opt/mssql/secrets